services:
  eq_mongodb:
    image: mongo:latest
    container_name: eq_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: eq_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://eq_mongodb:27017/bookstore_db
      - PORT=5000
      - JWT_SECRET=YourSuperSecretKey123!
    depends_on:
      - eq_mongodb
    networks:
      - app-network

  frontend-consumer:
    build: ./frontend-consumer
    container_name: eq_frontend
    ports:
      - "3000:5173"
    environment:
      - VITE_REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: eq_admin
    ports:
      - "3001:80"
    environment:
      - VITE_REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: